definitions:
  # Reusable definitions go in this section
  scripts:
    - &shorebird_install
      name: Install Shorebird CLI
      script: |
        # Install the Shorebird CLI
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
        # Set Shorebird PATH
        echo PATH="/Users/builder/.shorebird/bin:$PATH" >> $CM_ENV        
    - &flutter_analyze
      name: Run static code analysis
      script: flutter analyze
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties" 
    
workflows:
  # Define your workflows here
  release-android-workflow:
    name: Release Android Workflow
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - Android Apps KeyStore
      groups:
        - shorebird
        - google_play
      vars:
        PACKAGE_NAME: "com.immadisairaj.radiosai"
        GOOGLE_PLAY_TRACK: "internal"
      flutter: stable
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release
    scripts:
      - *flutter_analyze
      - *setup_local_properties
      - *shorebird_install   
      - name: Build with Shorebird
        script: |
          shorebird release android
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
  
  # !Note: Codemagic for iOS and shorebird won't work so commenting for now
  # Download xcode archive from shorebird into /Library/Developer/XCode/Archive/<date>/
  # go to Xcode > Window > Organizer
  # Custom upload the build archive to App Store Connect (uncheck manage version)
  
  # release-ios-workflow:
  #   name: Release iOS Workflow
  #   instance_type: mac_mini_m1
  #   integrations:
  #     app_store_connect: Codemagic Connect
  #   environment:
  #     ios_signing:
  #       distribution_type: app_store
  #       bundle_identifier: com.immadisairaj.saivoice
  #       # provisioning_profiles:
  #       #   - profile: SAI_VOICE_PROVISIONAL_CERTIFICATE
  #       # certificates:
  #       #   - certificate: APPLE_APP_DISTRIBUTION
  #     groups:
  #       - shorebird
  #     flutter: stable
  #   triggering:
  #     events:
  #       - push
  #     branch_patterns:
  #       - pattern: release
  #   scripts:
  #     - *flutter_analyze
  #     - *setup_local_properties
  #     - *shorebird_install
  #     - name: Set up code signing settings on Xcode project
  #       script: xcode-project use-profiles
  #     - name: Build with Shorebird
  #       script: | 
  #         shorebird release ios --no-codesign
  #   artifacts:
  #     - build/ios/ipa/*.ipa
  #     - /tmp/xcodebuild_logs/*.log
  #     - flutter_drive.log
  #   publishing:
  #     app_store_connect:
  #       auth: integration
  #       submit_to_testflight: true
  #       expire_build_submitted_for_review: true
  #       beta_groups:
  #         - Sai Voice Test Group
  #       submit_to_app_store: false
